# Generated by Django 5.2.5 on 2025-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
